apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ke.fullname" . }}
  labels:
    app: kubedex-exporter
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    "helm.sh/created": {{.Release.Time.Seconds | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubedex-exporter
      release: {{.Release.Name | quote }}
  template:
    metadata:
      labels:
        app: kubedex-exporter
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
      annotations:
        "prometheus.io/scrape": "{{- not .Values.service.enabled }}"
        "prometheus.io/port": "9484"
        "prometheus.io/path": "/"
    spec:
      restartPolicy: {{default "Always" .Values.restartPolicy}}
      containers:
      - name: "kubedex-exporter"
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        ports:
        - containerPort: 9484
          name: http
